### ISSUE TITLE
Submission?

### ISSUE THREAD

**Issue by chug2k** [konnguyen/CalculatorTip#1]
Hi - are you done with your submission? If so, please let me know. :smile:  Thanks for your work so far!

From http://courses.coderschool.vn/submission:

> Make sure to mention me, chug2k in the issue by typing “/cc @chug2k” in the body of the issue. We will then review your submission and respond in the issue with feedback.

/cc @marcusellison @harley @minhchau273

**Comment by chug2k** [comment]
Hi - I just gave very similar feedback to your colleague Tri:

Ah, I see you have emailed marcus@coderschool.vn. Thanks. Please read the instructions more carefully next time.

This is a fine submission! But you are missing one very small thing, also from the submission instructions at http://courses.coderschool.vn/submission:

> **Please note that you need to download LiceCap and you MUST include a GIF walkthrough of all required and optional stories in the README**

Once you do fix your README.md, I would be happy to accept you into the course.

Extra comments:
- Nice job with the flipping screen. :smile: 
- Please pay attention to compiler warnings. There are times when it's asking you to use `let` instead of `var`. 
- For more information about code formatting, please refer to: https://github.com/raywenderlich/swift-style-guide. You're pretty consistent, but try to be 100% clean. Perhaps you can write a better function name than `doYourStuff`. :stuck_out_tongue_closed_eyes: 
- Interesting job with the entering foreground notification to update your values! But I'm not quite sure what's going on with `reset_necessary`...

Please fix your README.md as soon as you can. Space in our class is filling up. 

/cc @marcusellison @harley @minhchau273

**Comment by konnguyen** [comment]
Hi @chug2k 
I have completed my submission with fixed README.md. Please take a look and feedback. Above comments, I have taken notes and write a better next time.
Thanks.
